version: '3.8'
services:
  app_laravel:
    build: .
    tty: true   # attache un terminal
    volumes:
      - .:/projet

  mariadb:
    build: "./mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbtest
    volumes: 
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/datadir:/var/lib/mysql
