version: '3.4'
services:
  app_laravel:
    build: .
    tty: true   # attache un terminal
    volumes:
      - .:/projet

  mariadb:
    build: "./mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mariadb/datadir:/var/lib/mysql
